let movies = [
	{"vote_count":2381,"id":299537,"vote_average":7.3,"title":"Captain Marvel","genre_ids":"Action | Adventure | Science Fiction","backdrop_path":"\/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg","overview":"The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.","release_date":"2019-03-06"},
	{"vote_count":1065,"id":166428,"vote_average":7.8,"title":"How to Train Your Dragon: The Hidden World","genre_ids":"Animation | Family | Adventure","backdrop_path":"\/h3KN24PrOheHVYs9ypuOIdFBEpX.jpg","overview":"As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.","release_date":"2019-01-03"},
	{"vote_count":74,"id":450001,"vote_average":5.5,"title":"Master Z: Ip Man Legacy","genre_ids":"Action","backdrop_path":"\/grtVFGJ4ts0nDAPpc1JWbBoVKTu.jpg","overview":"After being defeated by Ip Man, Cheung Tin Chi is attempting to keep a low profile. While going about his business, he gets into a fight with a foreigner by the name of Davidson, who is a big boss behind the bar district. Tin Chi fights hard with Wing Chun and earns respect.","release_date":"2018-12-20"},
	{"vote_count":394,"id":399361,"vote_average":6.3,"title":"Triple Frontier","genre_ids":"Action | Thriller | Crime","backdrop_path":"\/s9I2LmQMYCanl6DvC3X1AOHs2r8.jpg","overview":"Struggling to make ends meet, former special ops soldiers reunite for a high-stakes heist: stealing $75 million from a South American drug lord.","release_date":"2019-03-06"},
	{"vote_count":4640,"id":297802,"vote_average":6.8,"title":"Aquaman","genre_ids":"Action | Adventure | Fantasy | Science Fiction","backdrop_path":"\/9QusGjxcYvfPD1THg6oW3RLeNn7.jpg","overview":"Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.","release_date":"2018-12-07"},
	{"vote_count":1592,"id":399579,"vote_average":6.7,"title":"Alita: Battle Angel","genre_ids":"Action | Science Fiction | Thriller | Adventure","backdrop_path":"\/aQXTw3wIWuFMy0beXRiZ1xVKtcf.jpg","overview":"When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.","release_date":"2019-01-31"},
	{"vote_count":409,"id":512196,"vote_average":6.2,"title":"Happy Death Day 2U","genre_ids":"Horror | Mystery | Thriller | Science Fiction | Comedy","backdrop_path":"\/dhNJHBDacrZjSPtwaiwp3idpzxU.jpg","overview":"Collegian Tree Gelbman wakes up in horror to learn that she's stuck in a parallel universe. Her boyfriend Carter is now with someone else, and her friends and fellow students seem to be completely different versions of themselves. When Tree discovers that Carter's roommate has been altering time, she finds herself once again the target of a masked killer. When the psychopath starts to go after her inner circle, Tree soon realizes that she must die over and over again to save everyone.","release_date":"2019-02-13"},
	{"vote_count":104,"id":464504,"vote_average":5.9,"title":"A Madea Family Funeral","genre_ids":"Comedy","backdrop_path":"\/piGjUloiaq6qTpaDLisyDyEsx9i.jpg","overview":"A joyous family reunion becomes a hilarious nightmare as Madea and the crew travel to backwoods Georgia, where they find themselves unexpectedly planning a funeral that might unveil unpleasant family secrets.","release_date":"2019-03-01"},
	{"vote_count":12,"id":429471,"vote_average":5.5,"title":"Captive State","genre_ids":"Thriller | Science Fiction","backdrop_path":"\/6IZ84KFhNpy6htsJmwFVuK30pyp.jpg","overview":"Nearly a decade after occupation by an extraterrestrial force, the lives of a Chicago neighborhood on both sides of the conflict are explored.","release_date":"2019-03-15"},
	{"vote_count":1036,"id":400650,"vote_average":6.7,"title":"Mary Poppins Returns","genre_ids":"Fantasy | Family | Comedy","backdrop_path":"\/cwiJQXezWz876K3jS57Sq56RYCZ.jpg","overview":"In Depression-era London, a now-grown Jane and Michael Banks, along with Michael's three children, are visited by the enigmatic Mary Poppins following a personal loss. Through her unique magical skills, and with the aid of her friend Jack, she helps the family rediscover the joy and wonder missing in their lives.","release_date":"2018-12-13"},
	{"vote_count":863,"id":504172,"vote_average":6.5,"title":"The Mule","genre_ids":"Crime | Drama | Thriller","backdrop_path":"\/bTeRgkAavyw1eCtSkaww18wLYNP.jpg","overview":"Earl Stone, a man in his 80s who is broke, alone, and facing foreclosure of his business when he is offered a job that simply requires him to drive. Easy enough, but, unbeknownst to Earl, he’s just signed on as a drug courier for a Mexican cartel. He does so well that his cargo increases exponentially, and Earl hit the radar of hard-charging DEA agent Colin Bates.","release_date":"2018-12-14"},
	{"vote_count":108,"id":487297,"vote_average":5.4,"title":"What Men Want","genre_ids":"Comedy | Fantasy | Romance","backdrop_path":"\/umecegsPpKr2ZXA62Da9CQBVoIO.jpg","overview":"Magically able to hear what men are thinking, a sports agent uses her newfound ability to turn the tables on her overbearing male colleagues.","release_date":"2019-02-08"},
	{"vote_count":1762,"id":480530,"vote_average":6.6,"title":"Creed II","genre_ids":"Drama","backdrop_path":"\/6JHYYbvoSuQ95ceGx8Oeg8zzAjg.jpg","overview":"Between personal obligations and training for his next big fight against an opponent with ties to his family's past, Adonis Creed is up against the challenge of his life.","release_date":"2018-11-21"},
	{"vote_count":2425,"id":490132,"vote_average":8.3,"title":"Green Book","genre_ids":"Drama | Comedy | Music","backdrop_path":"\/78PjwaykLY2QqhMfWRDvmfbC6EV.jpg","overview":"Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.","release_date":"2018-11-16"},
	{"vote_count":9,"id":548066,"vote_average":4.7,"title":"Level 16","genre_ids":"Science Fiction","backdrop_path":"\/dSdZ9iAgoDyAh3AcXtdyS9GtBKu.jpg","overview":"The teenage girls of Vestalis Academy are meticulously trained in the art of being “clean girls,” practicing the virtues of perfect femininity. But what exactly are they being trained for? Vivien intends to find out.","release_date":"2019-03-01"},
	{"vote_count":1941,"id":404368,"vote_average":7.3,"title":"Ralph Breaks the Internet","genre_ids":"Family | Animation | Comedy | Fantasy","backdrop_path":"\/88poTBTafMXaz73vYi3c74g0y2k.jpg","overview":"Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope's video game, \"Sugar Rush.\" In way over their heads, Ralph and Vanellope rely on the citizens of the internet -- the netizens -- to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.","release_date":"2018-11-20"},
	{"vote_count":86,"id":445629,"vote_average":6.2,"title":"Fighting with My Family","genre_ids":"Comedy | Drama","backdrop_path":"\/mYKP6qcDUimVMAHQWLOuDHjO19S.jpg","overview":"Born into a tight-knit wrestling family, Paige and her brother Zak are ecstatic when they get the once-in-a-lifetime opportunity to try out for the WWE. But when only Paige earns a spot in the competitive training program, she must leave her loved ones behind and face this new cutthroat world alone. Paige's journey pushes her to dig deep and ultimately prove to the world that what makes her different is the very thing that can make her a star.","release_date":"2019-02-14"},
	{"vote_count":992,"id":449563,"vote_average":6.4,"title":"Isn't It Romantic","genre_ids":"Comedy | Fantasy | Romance","backdrop_path":"\/fPwJmIg6CVNNXUJvL1wgeexzwEp.jpg","overview":"For a long time, Natalie, an Australian architect living in New York City, had always believed that what she had seen in rom-coms is all fantasy. But after thwarting a mugger at a subway station only to be knocked out while fleeing, Natalie wakes up and discovers that her life has suddenly become her worst nightmare—a romantic comedy—and she is the leading lady.","release_date":"2019-02-13"},
	{"vote_count":471,"id":522681,"vote_average":6.4,"title":"Escape Room","genre_ids":"Horror | Thriller | Action","backdrop_path":"\/mWLljCmpqlcYQh7uh51BBMwCZwN.jpg", "overview":"Six strangers find themselves in circumstances beyond their control, and must use their wits to survive.","release_date":"2019-01-03"},
    {"vote_count":313,"id":280217,"vote_average":6.8,"title":"The Lego Movie 2: The Second Part","genre_ids":"Action | Adventure | Animation | Comedy | Family | Science Fiction | Fantasy","backdrop_path":"\/8kPozGb4BDrcWBSsGPrkULG2tP9.jpg","overview":"It's been five years since everything was awesome and the citizens are facing a huge new threat: LEGO DUPLO® invaders from outer space, wrecking everything faster than they can rebuild.","release_date":"2019-01-26"}
]


module.exports = {
    read: (req, res) => {
        res.status(200).send(movies)
	},

}
